name: kavita_healling_reanaissance
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  shared_preferences: ^2.5.2
  shared_preferences_windows: ^2.4.1
  google_fonts: ^6.2.1
  flutter_zoom_drawer: ^3.2.0
  simple_animations: ^5.0.2
  http: ^1.2.1
  dart_jsonwebtoken: ^2.14.0
  quickalert: ^1.1.0
  image_picker: ^1.1.2
  expandable_datatable: ^0.0.7
  data_table_2: ^2.5.12
  glassmorphism: ^3.0.0
  intl: ^0.20.2
  video_player: ^2.8.7
  chewie: ^1.10.0
  wakelock_plus: ^1.2.9
  file_picker: ^9.0.0
  dio: ^5.4.3+1
  flutter_launcher_icons: ^0.14.3
  card_slider: ^1.0.5
  flutter_countdown_timer: ^4.1.0
  url_launcher: ^6.3.0
  carousel_slider: ^5.0.0
  new_flutter_icons: ^0.0.4
  flutter_cors: ^1.5.0
  win32: ^5.5.0
  webview_flutter: ^4.10.0
  permission_handler: ^11.3.1
  video_compress: ^3.1.0
  tus_client_dart: ^2.5.0
  path_provider: ^2.0.11

  flutter_native_splash: ^2.2.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/images/appicon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"                # Background color of the splash screen
  image: assets/images/appicon.png   # Path to your splash logo
  fill: true                      # Image will be centered and scaled to fill
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFill

flutter:
  uses-material-design: true

  assets:
    - assets/images/appicon.png
    - assets/images/
    - assets/
